### PR TITLE
Fix casting bug in KleeInternalize

### PR DESCRIPTION
**Pull request by edmcman**

### CODE REVIEW

**Comment by edmcman** [comment]
The truncating cast was failing when a pointer was being returned.

**Comment by agurfinkel** [comment]
That's not the right fix. Upcasting and truncating was needed for i1 which
have store size of i8.

Give me a minute.

**Comment by edmcman** [comment]
I am not sure that you as the pass writer are responsible for enforcing the store size here.

**Comment by agurfinkel** [comment]
We are copying a scalar into memory, then using `klee_make_symbolic` to
initialize the memory.
The size of the scalar in memory is its store size. We have to go through
that, otherwise we might be allocating one bit on the stack, which is not
allowed.

**Comment by agurfinkel** [comment]
Another fix committed.

**Pull request closed without merging**
