### PR TITLE
[CI] Run clang-format on pull requests

### PR DESCRIPTION
**Pull request by kuhar**
This adds a github action that checks if the code modified by a pull requests is formatted. If not, the CI bot will complain.

This github actions workflow is implemented in pure bash and does not reference any third-party actions. This usually takes <10s to execute.

Thought you may find it useful. Feel free to adapt & modify.

### CODE REVIEW

**Comment by kuhar** [comment]
I've been using github actions with my other repos for a few months now and am pretty happy.

**Comment by agurfinkel** [comment]
wow. that's great! thank you

**Comment by agurfinkel** [comment]
how can this be enabled on only some branches? I'm in a process of moving to llvm8 and would like that on the new branch

**Comment by kuhar** [comment]
Sample pull request where formatting issues were found: https://github.com/kuhar/seahorn/pull/1.

@agurfinkel this will run on any branch that has this file. So if you want it on other branches, simply push this commit there. If you want to permanently exclude some branches, you can modify the `runs on` declaration: https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestbranchestags

**Comment by agurfinkel** [comment]
can you make the PR on dev8 branch then

**Comment by kuhar** [comment]
done

**Pull request merged**
