### PR TITLE
feat(opsem): support for filters in UfoOpSem

### PR DESCRIPTION
**Pull request by ScottWe**
UfoOpSem inherits from OperationalSemantics, which supports instruction filtering.
In UfoOpSem, the filter checks are disabled through function overrides.
This commit restores the filter check in UfoOpSem::isTracked.

Note that filter support breaks some assumptions made by OpSemVisitor.
Therefore, additional guards are added against m_sem::isTracked.

### CODE REVIEW

**Comment by agurfinkel** [comment]
@ScottWe some tests still fail. Do they fail for you locally as well? They pass on my version without your new commits. (but only in release mode)

**Comment by ScottWe** [comment]
@agurfinkel I can reproduce the failures locally.

The filter is only used in BmcPass, correct? So the failed tests should be unrelated to the filter. However, my commit also calls isTracked on new instructions. I suspect that isTracked doesn't work properly for one of those instructions.

I will take a closer look.

**Comment by ScottWe** [comment]
The last line is `UfoOpSem::isTracked(v)` is `return v.getType()->isIntegerTy();`. This returns false on call instructions with a void return type (e.g., assumes, asserts, function that might fail).

To fix this, I've added a conditional that will track call instructions, after all other checks have been made.

**Comment by agurfinkel** [comment]
why not make `isTracked` track all void functions by changing
`return v.getType()->isIntegerTy() || v.getType()->isVoidTy()` ?

**Comment by ScottWe** [comment]
That makes sense. I can't think of any reason not to. Updated.

**Comment by agurfinkel** [comment]
let's see that all tests pass

**Comment by ScottWe** [comment]
@agurfinkel Are you waiting on any revisions from me?

**Comment by agurfinkel** [comment]
no. was waiting for checks to pass and forgot to check

**Pull request merged**
