### PR TITLE
Add a regression test suite.

### PR DESCRIPTION
**Pull request by wuestholz**
I added a regression test suite. It uses LLVM's lit tool (also used by other tools such as Boogie, Dafny and KLEE) to run the tests.

### CODE REVIEW

**Comment by agurfinkel** [comment]
This is fantastic! Thank you.

Do you know how to use LLVM's LNT tool for regression testing as well?
http://llvm.org/docs/lnt/

**Comment by wuestholz** [comment]
@agurfinkel No, I didn't know about this. Looks interesting though. Thanks!

**Comment by agurfinkel** [comment]
It supposed to help with performance regression, i.e., difference in execution time and not just expected output. Would be really cool to have this for seahorn as well.

**Comment by wuestholz** [comment]
@agurfinkel Yeah, for Boogie and Dafny I used to manually check the running times of the continuous build (which includes running regression tests) once in a while. However, something more automated would be quite nice, especially since running times of the build would also increase if new tests were added.

**Pull request merged**
